# ffnet example XOR

Feed forward multi-layer perceptron demonstration program.

Given (a) the structure of a multilayer perceptron, (b) weight matrices (including bias), and (c) input data X, compute output Y

1) Data File: XOR Problem

In [34]:
import numpy as np
import pandas as pd
X = pd.read_csv('Ex_FFnetData.csv', header=None)

(K,d) = np.shape(X)

3) Evaluate the output of the xor problem. 

In [59]:
w1 = np.array([[1,5,-5], [-3,2,5],[4,-5,-1]]).T  # first layer weights top row is the bias
w2 = np.array([[-2.5,1,1,1]]) .T   # second layer weight. Frist element is the bias
print(w1)
print(w2)

[[ 1 -3  4]
 [ 5  2 -5]
 [-5  5 -1]]
[[-2.5]
 [ 1. ]
 [ 1. ]
 [ 1. ]]


In [60]:
np.hstack((np.ones((K,1)), X)).dot(w1)

array([[ 1.00000e+00, -3.00000e+00,  4.00000e+00],
       [ 4.44450e-01, -2.44445e+00,  3.88889e+00],
       [-1.11100e-01, -1.88890e+00,  3.77778e+00],
       [-6.66650e-01, -1.33335e+00,  3.66667e+00],
       [-1.22220e+00, -7.77800e-01,  3.55556e+00],
       [-1.77780e+00, -2.22200e-01,  3.44444e+00],
       [-2.33335e+00,  3.33350e-01,  3.33333e+00],
       [-2.88890e+00,  8.88900e-01,  3.22222e+00],
       [-3.44445e+00,  1.44445e+00,  3.11111e+00],
       [-4.00000e+00,  2.00000e+00,  3.00000e+00],
       [ 1.55555e+00, -2.77778e+00,  3.44445e+00],
       [ 1.00000e+00, -2.22223e+00,  3.33334e+00],
       [ 4.44450e-01, -1.66668e+00,  3.22223e+00],
       [-1.11100e-01, -1.11113e+00,  3.11112e+00],
       [-6.66650e-01, -5.55580e-01,  3.00001e+00],
       [-1.22225e+00,  2.00000e-05,  2.88889e+00],
       [-1.77780e+00,  5.55570e-01,  2.77778e+00],
       [-2.33335e+00,  1.11112e+00,  2.66667e+00],
       [-2.88890e+00,  1.66667e+00,  2.55556e+00],
       [-3.44445e+00,  2.22222e

In [61]:
import numpy as np
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [62]:
hactivation = sigmoid(np.hstack((np.ones((K,1)), X)).dot(w1))
output1 = sigmoid(np.hstack((np.ones((K,1)), hactivation)).dot(w2))
print(hactivation)
print(output1)

[[0.73105858 0.04742587 0.98201379]
 [0.60931886 0.07984536 0.97994249]
 [0.47225353 0.13136994 0.97763808]
 [0.33924737 0.20860578 0.97507565]
 [0.22754952 0.31479423 0.97222795]
 [0.144575   0.44467743 0.9690649 ]
 [0.08839833 0.58257426 0.96555469]
 [0.05270501 0.70866312 0.96166195]
 [0.0309348  0.80914281 0.9573487 ]
 [0.01798621 0.88079708 0.95257413]
 [0.82571388 0.05853678 0.9690652 ]
 [0.73105858 0.09777191 0.96555503]
 [0.60931886 0.15886732 0.96166231]
 [0.47225353 0.24766028 0.95734911]
 [0.33924737 0.36457078 0.95257458]
 [0.22754073 0.500005   0.94729449]
 [0.144575   0.63542691 0.94146322]
 [0.08839833 0.75233786 0.93503103]
 [0.05270501 0.84113134 0.92794615]
 [0.0309348  0.9022272  0.92015464]
 [0.89197737 0.07205385 0.94729499]
 [0.82571388 0.11920187 0.94146377]
 [0.73105858 0.19085564 0.93503164]
 [0.60931886 0.29133482 0.92794682]
 [0.47225353 0.41742331 0.92015538]
 [0.33923616 0.55533245 0.91160086]
 [0.22754073 0.68520361 0.90222809]
 [0.144575   0.79139257 0.89

In [63]:
import pandas as pd
df = pd.read_csv('Ex_FFnetData.csv', header=None)
df['y1']=1+5*df[0]-5*df[1]
df['y2']=-3+2*df[0]+5*df[1]
df['y3']=4-5*df[0]-df[1]
df_=df[['y1','y2','y3']].values

In [64]:
df2 = pd.DataFrame(sigmoid(df_))
df2['z']=df2[0]+df2[1]+df2[2]-2.5

In [65]:
sigmoid(df2['z'].values)

array([0.32311311, 0.30345622, 0.28521501, 0.27347331, 0.27181602,
       0.28056058, 0.29661431, 0.3149733 , 0.33124186, 0.34329549,
       0.34373715, 0.3305686 , 0.31644634, 0.30518296, 0.30077559,
       0.30466948, 0.31463574, 0.32646158, 0.33665926, 0.34373733,
       0.3569392 , 0.35123376, 0.34455647, 0.33818354, 0.33399575,
       0.33318149, 0.33514013, 0.33803726, 0.34025128, 0.34107417,
       0.36239842, 0.36326582, 0.36475998, 0.36611876, 0.36590933,
       0.36285038, 0.35696289, 0.34954787, 0.34202068, 0.33510683,
       0.36010854, 0.36596814, 0.37440457, 0.38356026, 0.38940735,
       0.38758472, 0.3768445 , 0.3602501 , 0.34249529, 0.32674915,
       0.35011386, 0.35953208, 0.37305944, 0.38824605, 0.3997481 ,
       0.40142676, 0.39028424, 0.36873778, 0.34293517, 0.31869429,
       0.33329251, 0.34540988, 0.36251904, 0.38168493, 0.39716952,
       0.40270651, 0.39464883, 0.3737398 , 0.34488153, 0.3148003 ,
       0.31241173, 0.32703699, 0.34690203, 0.36857339, 0.38643