### 预估字段编码

In [1]:
import pandas as pd

In [3]:
data={
    "color":['red','blue','red','red'],
    "bought":['yes','no','yes','yes']
     }

In [4]:
df=pd.DataFrame(data=data)

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
LabelEncoder= LabelEncoder()

In [13]:
df["bought"]=LabelEncoder.fit_transform(df["bought"])

In [14]:
df

color  bought
0   red       1
1  blue       0
2   red       1
3   red       1

In [11]:
LabelEncoder.classes_

array(['no', 'yes'], dtype=object)

In [12]:
LabelEncoder.inverse_transform(df["bought"])

array(['yes', 'no', 'yes', 'yes'], dtype=object)

### 特征编码，one hot编码

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   color   4 non-null      object
 1   bought  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 192.0+ bytes


In [21]:
from sklearn.preprocessing import OneHotEncoder

#### 稀疏矩阵

In [29]:
#oneHotEncoder = OneHotEncoder(sparse=False) 
oneHotEncoder = OneHotEncoder(sparse = False)

In [30]:
oneHotEncoder.fit(df[["color"]]) #只包含一列，但是要返回一个二维数组

OneHotEncoder(sparse=False)

In [31]:
oneHotEncoder.transform(df[["color"]])

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [43]:
from sklearn.datasets import load_breast_cancer

In [44]:
breast_cancer=load_breast_cancer()

In [45]:
print(breast_cancer["DESCR"])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [49]:
data=breast_cancer["data"]
target=breast_cancer["target"]

In [51]:
data.shape

(569, 30)

In [52]:
target.shape

(569,)

In [53]:
data[:10]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [54]:
target[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 合并不同列成一个大数组

In [55]:
import numpy as np

##### c_快捷方式，传入数组

In [57]:
all_datas=np.c_[data,target]

In [58]:
import pandas as pd
df=pd.DataFrame(np.c_[data, target],
                columns=list(breast_cancer["feature_names"])+["target"])

In [59]:
df.head(3)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   
2        19.69         21.25           130.0     1203.0          0.10960   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33            184.6      2019.0   
1                 0.05667  ...          23.41            158.8      1956.0   
2                 0.05999  ...          25.53            152.5      1709.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890     0.0  
1          0.2750                  0.08902     0.0  
2          0.3613                  0.08758     0.0  

[3 rows x 31 columns]

##### 拆分数据集为训练集和测试集：
##### 设置random_state种子：为随机生成器设置一个种子，以便您的训练测试分割始终是确定的。如果设置不同的种子，每次都不一样。
##### 设置test_size：表示要包含在采风中的测试数据集的比例

In [60]:
from sklearn.model_selection import train_test_split

##### X_train:训练集的特征数据
##### X_test:测试集的特征数据
##### Y_train:训练集的预估目标
##### Y_test:测试集的预估目标

In [68]:
X_train, X_test, Y_train, Y_test =train_test_split(
    data, target, random_state=40, test_size=0.25)

In [75]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((426, 30), (143, 30), (426,), (143,))

In [76]:
data.shape, target.shape

((569, 30), (569,))

##### 拆分成测试集和训练集
##### 查看如下三个数据的分布：
##### target：原数据的预估目标列
##### y_train: 训练集的预估目标列
##### y_test: 测试集的预估目标列

In [78]:
target.shape,  Y_train.shape, Y_test.shape

((569,), (426,), (143,))

##### 每个数据中，1的数据有多少，0的数据有多少（以比率的形式展示）

In [81]:
for name, array in zip(["target","Y_train","Y_test"],[target,Y_train, Y_test]):
    print()
    print(name)
    print(pd.Series(array).value_counts(normalize=True))


target
1    0.627417
0    0.372583
dtype: float64

Y_train
1    0.607981
0    0.392019
dtype: float64

Y_test
1    0.685315
0    0.314685
dtype: float64


##### 测试集数据分布不均匀，会导致模型训练时出现问题，用stratify来保持均匀

In [82]:
X_train, X_test, Y_train, Y_test =train_test_split(
    data, target, random_state=40, test_size=0.25, stratify=target)

In [83]:
for name, array in zip(["target","Y_train","Y_test"],[target,Y_train, Y_test]):
    print()
    print(name)
    print(pd.Series(array).value_counts(normalize=True))


target
1    0.627417
0    0.372583
dtype: float64

Y_train
1    0.626761
0    0.373239
dtype: float64

Y_test
1    0.629371
0    0.370629
dtype: float64
